---
- name: create keypair
  ec2_key:
    name: "{{ key_name }}"
    region: "{{ region }}"
  register: ec2_key

- name: download private key
  copy: content="{{ ec2_key.key.private_key }}" dest="./{{ key_name }}.pem" mode=0766
  when: ec2_key.changed
